version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/auth-server
hooks:
  ApplicationStop:
   - location: stop.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: init.sh
     timeout: 300
     runas: root
