name: Deploy to AWS

on:
  push:
    branches:
      - server

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Create Deployment
        id: deploy
        env:
          DESTINATION: auth-server
        run: |
          aws deploy create-deployment --ignore-application-stop-failures \
            --application-name ${{ env.DESTINATION }} \
            --deployment-group-name ${{ env.DESTINATION }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --file-exists-behavior RETAIN \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
