name: Server Build

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Build
      run: |
        git checkout -b server
        git checkout server
        cp package.json package-lock.json README.md tsconfig.json LICENSE server/


    - name: Prune
      run : |
        find . -type f -not -name 'server,appspec.yml,LICENSE,README.md' -delete

    - name: push
      run: |
        echo $(pwd)
        git config user.email "wolfemikl@gmail.com"
        git config user.name "Mikl Wolfe"
        git add server
        git commit -am 'Update server'
        git push -fu origin main:server
