name: Server Build

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        git checkout -b server
        git checkout server
        cp package.json package-lock.json README.md tsconfig.json LICENSE server/

    - name: Prune
      run : |
        prune() {
          echo "${1}";
          if
          [ "${1}" != "${PWD}" ] &&
          [ "${1}" != "${PWD}/server" ] &&
          [ "${1}" != "${PWD}/.github" ] &&
          [ "${1}" != "${PWD}/appspec.yml" ] &&
          [ "${1}" != "${PWD}/LICENSE" ] &&
          [ "${1}" != "${PWD}/README.md" ]; then
            rm -rf ${1};
        }
        export -f prune
        find . -maxdepth 1 | while read file; do prune ${file}; done

    - name: push
      run: |
        echo $(pwd)
        echo here: $(ls -a)
        echo status: $(git status)
        echo .git: $(ls -a .git)
        git config user.email "wolfemikl@gmail.com"
        git config user.name "Mikl Wolfe"
        git add server
        git commit -am 'Update server'
        git push -fu origin main:server
