name: Server Build

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        git checkout -b server
        git checkout server
        cp package.json package-lock.json README.md tsconfig.json LICENSE server/

    - name: Prune
      run : |
        prune() {
          echo "${1}";
          if
          [ "${1}" != "." ] &&
          [ "${1}" != ".." ] &&
          [ "${1}" != "./.git" ] &&
          [ "${1}" != "./.github" ] &&
          [ "${1}" != "./server" ] &&
          [ "${1}" != "./appspec.yml" ] &&
          [ "${1}" != "./LICENSE" ] &&
          [ "${1}" != "./README.md" ]; then
            rm -rf ${1};
          fi
        }
        export -f prune
        find . -maxdepth 1 | while read file; do prune ${file}; done

    - name: push
      env:
        GITHUB_TOKEN: ${{ secrets.DISPATCH_REPO }}
      run: |
        echo $(pwd)
        echo here: $(ls -a)
        echo status: $(git status)
        git checkout server
        git config user.email "wolfemikl@gmail.com"
        git config user.name "Mikl Wolfe"
        git config user.password ${{ env.GITHUB_TOKEN }}
        git add .
        git commit -am 'Update server'
        git push -fu origin server
